(fin-edu:history:gold)=
# Gold

...

In [1]:
#> Libraries
import numpy as np

import pandas as pd
# from IPython.display import display  # import not required, maybe

import plotly.express as px
import plotly.graph_objects as go
import plotly.io as pio
from plotly.subplots import make_subplots

import yfinance as yf

In [2]:
#> Mount GDrive if required - for Colab editing
from pathlib import Path

# Detect Colab and mount Drive if needed
try:
    from google.colab import drive
    IN_COLAB = True
    pio.renderers.default = "colab"
except ImportError:
    IN_COLAB = False
    pio.renderers.default = "iframe"

if IN_COLAB:
    drive.mount('/content/drive')
    %cd /content/drive/MyDrive/basics-books/repos/financial-edu/bbooks-financial-edu/ch/history

FILE_ROOT = Path.cwd()

print("Repo root:", FILE_ROOT)

Mounted at /content/drive
/content/drive/MyDrive/basics-books/repos/financial-edu/bbooks-financial-edu/ch/history
Repo root: /content/drive/MyDrive/basics-books/repos/financial-edu/bbooks-financial-edu/ch/history

In [3]:
#> Import Shiller data (.xls)
shiller_filen = str(FILE_ROOT) + "/../../code/data/shiller/ie_data.xls"
df_shiller = pd.read_excel(shiller_filen, sheet_name="Data", skiprows=7, engine="xlrd")

#> Import gold data: monthly prices (.csv)
gold_filen = str(FILE_ROOT) + "/../../code/data/gold/monthly.csv"
df_gold = pd.read_csv(gold_filen,)

In [4]:
#> Clean data
# Shiller
#> Remove non-data last row
df_shiller = df_shiller.iloc[:-1].copy()

#> Convert Data to proper datetime type
df_shiller["Date"] = df_shiller["Date"].map(lambda x: f"{x:.2f}")
df_shiller["Date"] = pd.to_datetime( df_shiller["Date"], format="%Y.%m")

In [5]:
"""
#> Inspection
display(df_shiller.head())
display(df_shiller.tail())
display(df_gold.head())
display(df_gold.tail())
"""

,Date,P,D,E,CPI,Fraction,Rate GS10,Price,Dividend,Price.1,...,CAPE,Unnamed: 13,TR CAPE,Unnamed: 15,Yield,Returns,Returns.1,Real Return,Real Return.1,Returns.2
0,1871-01-01,4.44,0.26,0.4,12.464061,1871.041667,5.32,114.692610,6.716234,114.692610,...,NaN,NaN,NaN,NaN,NaN,1.004177,1.000000,0.130609,0.092504,0.038106
1,1871-02-01,4.5,0.26,0.4,12.844641,1871.125000,5.323333,112.798304,6.517235,113.341406,...,NaN,NaN,NaN,NaN,NaN,1.004180,0.974424,0.130858,0.094635,0.036224
2,1871-03-01,4.61,0.26,0.4,13.034972,1871.208333,5.326667,113.868306,6.422074,114.954311,...,NaN,NaN,NaN,NaN,NaN,1.004183,0.964209,0.130951,0.096186,0.034765
3,1871-04-01,4.74,0.26,0.4,12.559226,1871.291667,5.33,121.514327,6.665343,123.233997,...,NaN,NaN,NaN,NaN,NaN,1.004185,1.004919,0.122056,0.090972,0.031084
4,1871-05-01,4.86,0.26,0.4,12.273812,1871.375000,5.333333,127.487866,6.820339,129.868479,...,NaN,NaN,NaN,NaN,NaN,1.004188,1.032591,0.122638,0.089488,0.033150

,Date,P,D,E,CPI,Fraction,Rate GS10,Price,Dividend,Price.1,...,CAPE,Unnamed: 13,TR CAPE,Unnamed: 15,Yield,Returns,Returns.1,Real Return,Real Return.1,Returns.2
1850,2025-03-01,5683.983333,76.145301,216.69,319.799,2025.208333,4.28,5722.525411,76.661629,3.845325e+06,...,34.784750,NaN,37.348615,NaN,0.016749,1.003567,39.625790,NaN,NaN,NaN
1851,2025-04-01,5369.495714,76.546867,NaN,320.795,2025.291667,4.28,5389.121125,76.826645,3.625592e+06,...,32.621270,NaN,35.015341,NaN,0.018767,0.992343,39.643654,NaN,NaN,NaN
1852,2025-05-01,5810.919524,76.948434,NaN,321.465,2025.375000,4.42,5820.002899,77.068716,3.919793e+06,...,35.172023,NaN,37.769849,NaN,0.014834,1.006896,39.258095,NaN,NaN,NaN
1853,2025-06-01,6029.9515,77.350000,NaN,321.8,2025.458333,4.38,6033.090148,77.390261,4.067652e+06,...,36.394510,NaN,39.098992,NaN,0.014026,1.010099,39.487674,NaN,NaN,NaN
1854,2025-07-01,6279.35,NaN,NaN,321.9675,2025.541667,4.3,6279.350000,NaN,4.233686e+06,...,37.806545,NaN,40.590130,NaN,0.013847,NaN,39.865727,NaN,NaN,NaN

      Date  Price
0  1833-01  18.93
1  1833-02  18.93
2  1833-03  18.93
3  1833-04  18.93
4  1833-05  18.93

         Date    Price
2306  2025-03  2983.25
2307  2025-04  3217.64
2308  2025-05  3309.49
2309  2025-06  3352.66
2310  2025-07  3340.15

In [6]:
fig = go.Figure()
fig.add_trace(go.Scatter(x=df_gold['Date'], y=df_gold['Price']))
fig.update_yaxes(type="log")
fig.show()